//tealium universal tag - utag.106 ut4.0.201603181918, Copyright 2016 Tealium.com Inc. All Rights Reserved.
if(typeof utag.ut=="undefined"){utag.ut={};}
utag.ut.libloader2=function(o,a,b,c,l){a=document;b=a.createElement('script');b.language='javascript';b.type='text/javascript';b.src=o.src;if(o.id){b.id=o.id};if(typeof o.cb=='function'){b.hFlag=0;b.onreadystatechange=function(){if((this.readyState=='complete'||this.readyState=='loaded')&&!b.hFlag){b.hFlag=1;o.cb()}};b.onload=function(){if(!b.hFlag){b.hFlag=1;o.cb()}}}
l=o.loc||'head';c=a.getElementsByTagName(l)[0];if(c){if(l=='script'){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}
utag.DB("Attach to "+l+": "+o.src)}}
var _tealium_kenshoo_params106=[];try{(function(id,loader,u){try{u=utag.o[loader].sender[id]={}}catch(e){u=utag.sender[id]};u.ev={'view':1,'link':1};u.data={};u.data.kid="1168";u.data.id="f1681441-ed23-4dcc-bbd6-b6225abc34af";u.data.type="";u.map={"_kenshooConversionType":"type"};u.extend=[function(a,b){if(typeof b['cp.observepoint']!=='undefined'&&b['cp.observepoint']=='yes'){return false}},function(a,b){try{if(b['video_event']=='video_start'){b['_kenshooConversionType']='video_view';b['kenshoo_send_flag']='Y'}}catch(e){utag.DB(e)}},function(a,b){if(typeof b.kenshoo_send_flag=="undefined"){return false;}}];u.send=function(a,b,c,d,e,f){if(u.ev[a]||typeof u.ev.all!="undefined"){for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){if(typeof utag_err!='undefined'){utag_err.push({e:'extension error:'+e,s:utag.cfg.path+'utag.'+id+'.js',l:c,t:'ex'})}}};c=[];for(d in utag.loader.GV(u.map)){if(typeof b[d]!='undefined'&&b[d]!=''){e=u.map[d].split(',');for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
u.data.type=u.data.type||"conv";u.data.val=u.data.val||(b._csubtotal!==undefined?b._csubtotal:"");u.data.orderId=u.data.orderId||(b._corder!==undefined?b._corder:"");u.data.promoCode=u.data.promoCode||(b._cpromo!==undefined?b._cpromo:"");u.data.valueCurrency=u.data.valueCurrency||b._ccurrency||"USD";c.push("id="+u.data.id);c.push("type="+u.data.type);c.push("val="+u.data.val);c.push("orderId="+u.data.orderId);c.push("promoCode="+u.data.promoCode);c.push("valueCurrency="+u.data.valueCurrency);window._tealium_kenshoo_params106=c.slice(0);u.kenshoo_callback=function(){k_trackevent(_tealium_kenshoo_params106,"1168");}
u.base_url="//"+u.data.kid+".xg4ken.com/media/getpx.php?cid="+u.data.id;utag.ut.libloader2({src:u.base_url,id:"_tealium_kenshoo_106",cb:u.kenshoo_callback});}}
try{utag.o[loader].loader.LOAD(id)}catch(e){utag.loader.LOAD(id)}})('106','ti.main');}catch(e){}
