//tealium universal tag - utag.4 ut4.0.201603181918, Copyright 2016 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader,u){try{u=utag.o[loader].sender[id]={}}catch(e){u=utag.sender[id]};u.ev={'view':1};u.qsp_delim="&";u.kvp_delim="=";u.qs_delim="?";u.tag_type="script";u.base_url="datacloud.tealiumiq.com/ti/main/16/i.js";u.static_params="jsonp=utag.ut.getvisitorid";u.map={"_random_number":"cb"};u.extend=[function(a,b){if(typeof b['cp.observepoint']!=='undefined'&&b['cp.observepoint']=='yes'){return false}},function(a,b){utag.ut.getvisitorid=function(data){utag.DB("Starting cookie logic");utag.DB("tiSessionID or chipset cookie not defined - start checking server data");utag.DB("Data from server: ");utag.DB(data);var tiSessionID=utag.data['cp.tiSessionID']||utag.data['cp.utag_main_v_id']||"";try{utag.DB("Testing sessionID. Current value: ");utag.DB(tiSessionID);if(data.tvt&&data.tvt[0]&&data.tvt[0].t1){utag.DB("Server match found");tiSessionID=data.tvt[0].t1;}else{utag.DB("No server match found. Storing new value.");utag.ut.loader({type:'img',src:"//datacloud.tealiumiq.com/ti/main/16/i.gif?t1="+tiSessionID+"&cb="+Math.random()});}}catch(e){utag.DB(e);}
if(tiSessionID){utag.DB("Setting local cookie with value: ");utag.DB(tiSessionID);tl_setCookie('tiSessionID',tiSessionID,60*24*365*2);utag_data['cp.tiSessionID']=tiSessionID;utag.data['cp.tiSessionID']=tiSessionID;}
var currChipset=utag.data['cp.tiPermID']||utag.data['tcPermanentId']||utag.data['cp.chipset']||"";var chipset="";try{utag.DB("Testing chipset. Current value: ");utag.DB(chipset);var found=false;if(data.tvt){utag.DB("Checking server data");for(i=data.tvt.length-1;i>-1;i--){if(data.tvt[i].t2){chipset=data.tvt[i].t2;found=true;}
utag.DB("Record searched: ");utag.DB(data.tvt[i]);utag.DB("Match found: "+found);if(found){utag.DB("Found a match. Skipping rest of data to save time.");break;}}}
if(currChipset&&(!found||currChipset!=chipset)){utag.DB("No server record found. Storing the new value.");utag.ut.loader({type:'img',src:"//datacloud.tealiumiq.com/ti/main/16/i.gif?t1="+tiSessionID+"&t2="+currChipset+"&cb="+Math.random()});}}catch(e){utag.DB(e);}
chipset=currChipset||chipset;if(chipset){utag.DB("Setting local cookie with value: ");utag.DB(chipset);tl_setCookie('chipset',chipset,60*24*365*1);utag_data['cp.chipset']=chipset;utag.data['cp.chipset']=chipset;if(typeof utag.loader.RC('tiPermID')!='object')
utag.loader.SC('tiPermID',{},'da');}
utag.DB("Logic done. Firing SC tag manually.");utag.view(utag_data,null,[2,87]);}}];u.send=function(a,b){if(u.ev[a]||typeof u.ev.all!="undefined"){for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){if(typeof utag_err!='undefined'){utag_err.push({e:'extension error:'+e,s:utag.cfg.path+'utag.'+id+'.js',l:c,t:'ex'})}}};var c,d,e,f;c=[];for(d in utag.loader.GV(u.map)){if(typeof b[d]!="undefined"&&b[d]!=""){e=u.map[d].split(",");for(f=0;f<e.length;f++){if(e[f]=="qsp_delim"||e[f]=="kvp_delim"||e[f]=="qs_delim"||e[f]=="base_url"||e[f]=="secure_base_url"){u[e[f]]=b[d];}else{c.push(e[f]+u.kvp_delim+encodeURIComponent(b[d]));}}}}
u.secure_base_url=u.secure_base_url||"datacloud.tealiumiq.com/ti/main/16/i.js"||u.base_url;u.url=(location.protocol=="https:"?u.secure_base_url:u.base_url);if(u.url.indexOf("http")!=0&&u.url.indexOf("/")!=0){u.url="//"+u.url;}
if(u.url.indexOf(u.qs_delim)<0&&(c.length>0||u.static_params.length>0)){u.url+=u.qs_delim}
if(u.static_params){if(c.length>0){u.url+=u.static_params+u.qsp_delim;}else{u.url+=u.static_params;}}
if(u.tag_type=="img"){u.img=new Image();u.img.src=u.url+c.join(u.qsp_delim);}else if(u.tag_type=="script"){u.s=document.getElementsByTagName("script")[0];u.scr=document.createElement("script");u.scr.type="text/javascript";u.scr.src=u.url+c.join(u.qsp_delim);u.s.parentNode.insertBefore(u.scr,u.s);}else{d=document.createElement("iframe");d.setAttribute('id','4');d.setAttribute('height','1');d.setAttribute('width','1');d.setAttribute('style','display:none');d.setAttribute('src',u.url+c.join(u.qsp_delim));document.body.appendChild(d);}}}
try{utag.o[loader].loader.LOAD(id)}catch(e){utag.loader.LOAD(id)}})('4','ti.main');}catch(e){}
